import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.95
blur = true
dynamic_title = true
padding.x = 5
padding.y = 10
dynamic_padding = false
# decorations = none

[scrolling]
history = 5000

[font]
size = 15
normal.family = "DankMono Nerd Font"

# Fixes tmux bg
[colors]
transparent_background_colors = true

[selection]
save_to_clipboard = true

[cursor]
style = {shape = "Beam", blinking = "Always"}

[keyboard]
bindings = [ {key="F11", action="ToggleFullscreen"} ]
