format = """$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$line_break\
$jobs\
$character"""
# format_right = """$all"""
palette = "catppuccin_mocha"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[cmd_duration]
disabled = true

[directory]
style = "green"
truncation_length = 3
truncate_to_repo = false

[gcloud]
detect_env_vars = ["GCP_PROJECT", "CLOUDSDK_CORE_PROJECT"]

[git_state]
format = '[ \($state( $progress_current of $progress_total)\)]($style)'
style = 'bold teal'

[git_branch]
symbol = ""
style = 'sky'
format = """on [$symbol $branch(:$remote_branch)]($style)"""

[git_metrics]
disabled = true

[git_status]
ahead = "[ ](bold flamingo)"
behind = "[ ](bold blue)"
conflicted = '[ ](bold red)'
untracked = "[ ](bold yellow)"
staged = "[ ](bold green)"
modified = "[ ](bold peach)"
stashed = "[󰦤 ](bold lavender)"
deleted = ''
renamed = "[󰳟 ](bold rose)"
format = '([ $all_status$ahead_behind]($style) )'

[jobs]
style = "surface2"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
